### PR TITLE
Revised PR for adding bower

### PR DESCRIPTION
**Pull request by ShashankaNataraj**
Original issue raised at: https://github.com/h5bp/Effeckt.css/issues/309

1. Added bower.json with jQuery and modernizr dependencies
2. Added a gitignore entry with bower
3. Changed gruntfile copy task to include copying of jQuery and modernizr
4. Changed script inclusion from cdn to bower in layout.hbs

From code review comments on previous PR: https://github.com/h5bp/Effeckt.css/pull/310, 

1. I versioned bower and package.json at 0.5.0.
2. Added EOF line in bower.json

### CODE REVIEW

**Comment by ShashankaNataraj** [comment]
@grayghostvisuals @arthurvr Here you go

**Comment by ShashankaNataraj** [comment]
@arthurvr @grayghostvisuals err guys? Can you please merge / comment?

**Comment by arthurvr** [comment]
cc @h5bp/effeckt-css

**Comment by joshyop** [comment]
> cc @h5bp/effeckt-css

@arthurvr you are such a lame ass .... after you say that you welcome contributions ... you dont merge just delegate it to some inactive members ... lame ass

**Comment by arthurvr** [comment]
well, we definitly welcome contributions but I'm just not the right one to review it. I've never been involved with effeckt. I don't even know this codebase :) If nobody from the team comes in the review this in a short time though, I'm probably gonna review and merge this in anyways.

**Pull request merged**
